name: CI

on: [ "push" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v3
        with:
          verbosity: Diagnostic

      - uses: actions/upload-artifact@v4
        with:
          name: AleLuduMod.dll
          path: src/AleLuduMod/bin/Release/net6.0/AleLuduMod.dll
